-- VHDL Entity RISCV_lib.ALU.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 15:08:05 05/24/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY ALU IS
   PORT( 
      alu_in_2    : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      ex_alu_mode : IN     alu_mode_type;
      ex_rs1      : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      ex_alu_out  : OUT    std_logic_vector (WORD_WIDTH-1 DOWNTO 0)
   );

-- Declarations

END ALU ;

