-- VHDL Entity RISCV_lib.clk_res_gen.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 13:53:08 06/21/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

ENTITY clk_res_gen IS
   PORT( 
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );

-- Declarations

END clk_res_gen ;

