-- VHDL Entity RISCV_lib.clk_res_gen.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 12:48:55 07/05/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;

ENTITY clk_res_gen IS
   PORT( 
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );

-- Declarations

END clk_res_gen ;

