-- VHDL Entity RISCV_lib.DBPU.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 16:44:45 06/28/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
library RISCV_lib;
use RISCV_lib.constants.all;
use RISCV_lib.data_types.all;
use RISCV_lib.isa.all;

entity DBPU is
  port (
    ex_alu_mode : in alu_mode_type;
    ex_alu_out : in word;
    ex_dbpu_addr_sel : in std_logic;
    ex_dbpu_mode : in std_logic;
    ex_imm : in word;
    ex_next_PC : in word;
    ex_sbta : in word;
    ex_dbta_valid : out std_logic;
    ex_jmp_target : out word
  );

  -- Declarations

end DBPU;