-- VHDL Entity RISCV_lib.DBPU.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 18:08:26 06/21/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY DBPU IS
   PORT( 
      ex_alu_mode      : IN     alu_mode_type;
      ex_alu_out       : IN     word;
      ex_dbpu_addr_sel : IN     std_logic;
      ex_dbpu_mode     : IN     std_logic;
      ex_imm           : IN     word;
      ex_next_PC       : IN     word;
      ex_rs1           : IN     word;
      ex_sbta          : IN     word;
      ex_dbta_valid    : OUT    std_logic;
      ex_jmp_target    : OUT    word
   );

-- Declarations

END DBPU ;

