-- VHDL Entity RISCV_lib.decoder.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 15:25:03 05/31/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY decoder IS
   PORT( 
      op_code            : IN     word;
      dec_alu_mode       : OUT    alu_mode_type;
      dec_imm_type       : OUT    imm_type;
      dec_mem_mode       : OUT    mem_mode;
      dec_mux_fw_mem_sel : OUT    fwd_sel;
      dec_mux_fw_rs1_sel : OUT    fwd_sel;
      dec_mux_fw_rs2_sel : OUT    fwd_sel;
      dec_mux_memory     : OUT    std_logic;
      dec_target_reg     : OUT    rf_storage_addr;
      sel_rs1            : OUT    rf_storage_addr;
      sel_rs2            : OUT    rf_storage_addr
   );

-- Declarations

END decoder ;

