-- VHDL Entity RISCV_lib.ex_reg.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 17:44:57 05/17/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY ex_reg IS
   PORT( 
      clk           : IN     std_logic;
      ex_alu_out    : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      ex_target_reg : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      res_n         : IN     std_logic;
      me_out        : OUT    integer RANGE 0 TO 4;
      me_target_reg : OUT    std_logic_vector (WORD_WIDTH-1 DOWNTO 0)
   );

-- Declarations

END ex_reg ;

