-- VHDL Entity RISCV_lib.ex_reg.interface
--
-- Created:
--          by - tzndirr.meyer (pc084)
--          at - 16:43:37 06/15/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY ex_reg IS
   PORT( 
      clk               : IN     std_logic;
      ex_alu_out        : IN     word;
      ex_mem_mode       : IN     mem_mode;
      ex_mux_fw_mem_sel : IN     fwd_sel;
      ex_target_reg     : IN     rf_storage_addr;
      res_n             : IN     std_logic;
      me_alu_out        : OUT    word;
      me_mem_mode       : OUT    mem_mode;
      me_target_reg     : OUT    rf_storage_addr
   );

-- Declarations

END ex_reg ;

