-- VHDL Entity RISCV_lib.if_reg.interface
--
-- Created:
--          by - tzndirr.meyer (pc084)
--          at - 14:35:53 06/14/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY if_reg IS
   PORT( 
      clk        : IN     std_logic;
      if_op_code : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      next_PC    : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      res_n      : IN     std_logic;
      stall      : IN     std_logic;
      op_code    : OUT    word
   );

-- Declarations

END if_reg ;

