-- VHDL Entity RISCV_lib.im.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 11:59:06 06/28/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY im IS
   PORT( 
      if_pc     : IN     word;
      res_n     : IN     std_logic;
      if_im_out : OUT    word
   );

-- Declarations

END im ;

