-- VHDL Entity RISCV_lib.im.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 18:09:37 07/12/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY im IS
   PORT( 
      data_valid  : IN     std_logic;
      if_pc       : IN     word;
      loading     : IN     std_logic;
      res_n       : IN     std_logic;
      sd_op_code  : IN     word;
      if_im_out   : OUT    word;
      load_op_mem : OUT    std_logic
   );

-- Declarations

END im ;

