-- VHDL Entity RISCV_lib.Imm_Gen.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 15:25:54 05/31/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY Imm_Gen IS
   PORT( 
      dec_imm_type : IN     imm_type;
      op_code      : IN     word;
      dec_imm      : OUT    word
   );

-- Declarations

END Imm_Gen ;

