-- VHDL Entity RISCV_lib.me_reg.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 15:58:07 05/24/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY me_reg IS
   PORT( 
      clk           : IN     std_logic;
      me_alu_out    : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      me_target_reg : IN     rf_storage_addr;
      res_n         : IN     std_logic;
      wb_data       : OUT    std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      wb_traget_reg : OUT    rf_storage_addr
   );

-- Declarations

END me_reg ;

