-- VHDL Entity RISCV_lib.Memory.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 17:08:06 05/31/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY Memory IS
   PORT( 
      clk               : IN     std_logic;
      me_alu_out        : IN     word;
      me_mem_mode       : IN     mem_mode;
      me_store_data_fwd : IN     word;
      res_n             : IN     std_logic;
      me_load_data      : OUT    word
   );

-- Declarations

END Memory ;

