-- VHDL Entity RISCV_lib.mux_memory.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 15:18:17 05/31/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY mux_memory IS
   PORT( 
      me_alu_out  : IN     word;
      me_mem_mode : IN     mem_mode;
      sig0        : IN     std_logic;
      me_me_out   : OUT    std_logic
   );

-- Declarations

END mux_memory ;

