-- VHDL Entity RISCV_lib.mux_bpu_ra.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 13:52:33 06/28/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY mux_bpu_ra IS
   PORT( 
      alu_out       : IN     word;
      ex_jmp_target : IN     word;
      ex_sbta_valid : IN     std_logic;
      ex_alu_out    : OUT    word
   );

-- Declarations

END mux_bpu_ra ;

