-- VHDL Entity RISCV_lib.mux_fw_memory.interface
--
-- Created:
--          by - tzndirr.meyer (pc084)
--          at - 16:54:21 06/15/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY mux_fw_memory IS
   PORT( 
      ex_mux_fw_mem_sel : IN     fwd_sel;
      ex_rs2_fwd        : IN     word;
      me_me_out         : IN     word;
      me_store_data_fwd : OUT    word
   );

-- Declarations

END mux_fw_memory ;

