-- VHDL Entity RISCV_lib.mux_fw_memory.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 15:25:03 05/31/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY mux_fw_memory IS
   PORT( 
      me_mux_fw_mem_sel : IN     fwd_sel;
      me_rs2_fwd        : IN     word;
      wb_data           : IN     word;
      me_store_data_fwd : OUT    word
   );

-- Declarations

END mux_fw_memory ;

