-- VHDL Entity RISCV_lib.mux_alu.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 17:44:57 05/17/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY mux_alu IS
   PORT( 
      ex_imm         : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      ex_mux_alu_sel : IN     std_logic;
      sig0           : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      alu_in_2       : OUT    std_logic_vector (WORD_WIDTH-1 DOWNTO 0)
   );

-- Declarations

END mux_alu ;

