-- VHDL Entity RISCV_lib.RF.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 17:44:57 05/17/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY RF IS
   PORT( 
      res_n         : IN     std_logic;
      sel_rs1       : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      sel_rs2       : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      wb_data       : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      wb_traget_reg : IN     std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      dec_rs1       : OUT    std_logic_vector (WORD_WIDTH-1 DOWNTO 0);
      dec_rs2       : OUT    std_logic_vector (WORD_WIDTH-1 DOWNTO 0)
   );

-- Declarations

END RF ;

