--
-- VHDL Architecture RISCV_lib.RISCV_tb.struct
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 12:09:55 05/31/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;

LIBRARY RISCV_lib;

ARCHITECTURE struct OF RISCV_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL res_n : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic ;
      res_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT riscv
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY RISCV_lib.clk_res_gen;
   FOR ALL : riscv USE ENTITY RISCV_lib.riscv;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   U_0 : riscv
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );

END struct;
