--
-- VHDL Architecture RISCV_lib.RISCV_tb.struct
--
-- Created:
--          by - flxbrggr.meyer (pc087)
--          at - 14:19:46 07/15/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;


ARCHITECTURE struct OF RISCV_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk        : std_logic;
   SIGNAL cs_bo      : std_logic;
   SIGNAL hex_disp0  : hex_disp_type;
   SIGNAL hex_disp1  : hex_disp_type;
   SIGNAL hex_disp2  : hex_disp_type;
   SIGNAL hex_disp3  : hex_disp_type;
   SIGNAL keys       : keys_type;
   SIGNAL leds_green : leds_green_type;
   SIGNAL leds_red   : leds_red_type;
   SIGNAL miso_i     : std_logic;
   SIGNAL res_n      : std_logic;
   SIGNAL sclk       : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic ;
      res_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT riscv
   PORT (
      clk        : IN     std_logic ;
      keys       : IN     keys_type ;
      miso_i     : IN     std_logic ;
      res_n      : IN     std_logic ;
      cs_bo      : OUT    std_logic ;
      hex_disp0  : OUT    hex_disp_type ;
      hex_disp1  : OUT    hex_disp_type ;
      hex_disp2  : OUT    hex_disp_type ;
      hex_disp3  : OUT    hex_disp_type ;
      leds_green : OUT    leds_green_type ;
      leds_red   : OUT    leds_red_type ;
      sclk       : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY RISCV_lib.clk_res_gen;
   FOR ALL : riscv USE ENTITY RISCV_lib.riscv;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   U_0 : riscv
      PORT MAP (
         clk        => clk,
         keys       => keys,
         miso_i     => miso_i,
         res_n      => res_n,
         cs_bo      => cs_bo,
         hex_disp0  => hex_disp0,
         hex_disp1  => hex_disp1,
         hex_disp2  => hex_disp2,
         hex_disp3  => hex_disp3,
         leds_green => leds_green,
         leds_red   => leds_red,
         sclk       => sclk
      );

END struct;
