-- VHDL Entity RISCV_lib.riscv.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 12:09:54 05/31/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;

ENTITY riscv IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic
   );

-- Declarations

END riscv ;

