-- VHDL Entity RISCV_lib.RISCV_tb.symbol
--
-- Created:
--          by - flxbrggr.meyer (pc085)
--          at - 16:03:56 05/10/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY RISCV_tb IS
-- Declarations

END RISCV_tb ;

