-- VHDL Entity RISCV_lib.SD_Controller.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 13:55:51 07/19/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY SD_Controller IS
   PORT( 
      clk         : IN     std_logic;
      load_op_mem : IN     std_logic;
      miso_i      : IN     std_logic;
      res_n       : IN     std_logic;
      cs_bo       : OUT    std_logic;
      data_valid  : OUT    std_logic;
      loading     : OUT    std_logic;
      sclk_o      : OUT    std_logic;
      sp_op_code  : OUT    word
   );

-- Declarations

END SD_Controller ;

