-- VHDL Entity RISCV_lib.SD_Fetch.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 16:17:02 07/14/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
USE IEEE.math_real.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY SD_Fetch IS
   PORT( 
      busy_o      : IN     std_logic;
      clk         : IN     std_logic;
      data_o      : IN     std_logic_vector (7 DOWNTO 0);
      error_o     : IN     std_logic_vector (15 DOWNTO 0);
      hndShk_o    : IN     std_logic;
      load_op_mem : IN     std_logic;
      res_n       : IN     std_logic;
      addr_i      : OUT    std_logic_vector (31 DOWNTO 0);
      continue_i  : OUT    std_logic;
      data_valid  : OUT    std_logic;
      hndShk_i    : OUT    std_logic;
      loading     : OUT    std_logic;
      rd_i        : OUT    std_logic;
      reset_i     : OUT    std_logic;
      sp_op_code  : OUT    word
   );

-- Declarations

END SD_Fetch ;

