-- VHDL Entity RISCV_lib.SdCardCtrl.interface
--
-- Created:
--          by - flxbrggr.meyer (pc084)
--          at - 16:08:25 07/14/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.all;
USE IEEE.math_real.all;
LIBRARY RISCV_lib;
USE RISCV_lib.constants.all;
USE RISCV_lib.data_types.all;
USE RISCV_lib.isa.all;

ENTITY SdCardCtrl IS
   GENERIC( 
      FREQ_G          : real       := 50.0;            --Master clock frequency (MHz)
      INIT_SPI_FREQ_G : real       := 0.4;             --Slow SPI clock freq. during initialization (MHz)
      SPI_FREQ_G      : real       := 25.0;            --Operational SPI frequency to the SD Card (MHz)
      BLOCK_SIZE_G    : natural    := 512;             --Number of bytes in an  SD card block or sector (Maybe set to 4?)
      CARD_TYPE_G     : CARDType_t := SDHC_CARD_E      --Type of SD Card connected to controller
   );
   PORT( 
      addr_i     : IN     std_logic_vector (31 DOWNTO 0);
      clk        : IN     std_logic;
      continue_i : IN     std_logic;
      data_i     : IN     std_logic_vector (7 DOWNTO 0);
      hndShk_i   : IN     std_logic;
      miso_i     : IN     std_logic;
      rd_i       : IN     std_logic;
      reset_i    : IN     std_logic;
      wr_i       : IN     std_logic;
      busy_o     : OUT    std_logic;
      cs_bo      : OUT    std_logic;
      data_o     : OUT    std_logic_vector (7 DOWNTO 0);
      error_o    : OUT    std_logic_vector (15 DOWNTO 0);
      hndShk_o   : OUT    std_logic;
      mosi_o     : OUT    std_logic;
      sclk_o     : OUT    std_logic
   );

-- Declarations

END SdCardCtrl ;

